リザルト画面のプロトタイプを作成
ParachanActionGame-Project/ParachanActionGame pull request #10
Opened 2021-09-29 10:57 UTC by Papyrustaro

2021-09-29 11:07 UTC, Jumpaku requested changes
以下に対応して欲しいです．

* [ ] リザルトシーン用のParachanクラスの追加
* [ ] スタートへ戻るためのボタンの追加

2021-09-29 11:16 UTC, Papyrustaro commented
@Jumpaku 
> * [ ]  リザルトシーン用のParachanクラスの追加

メインゲームで使用する予定のParachanクラスを流用せずに、リザルト用のParachanクラスを作成したほうがいいですか？
もし新たに作成するなら、Parachanクラスですでに実装してある描画と跳ね返り処理の実装をmainに反映させてから作成したいです。

2021-09-29 11:21 UTC, Jumpaku commented
同じ動きになるとは限らないのでupdateとdrawの実装を既存のものと分けておいた方が良いと思います．リザルト用のParachanクラスのupdateとdrawは現時点では仮の実装で構いません．

2021-09-29 11:26 UTC, Jumpaku commented
あと以下の機能とかも追加できますか？

* [ ] スコアのファイル保存（仮実装）
* [ ] Tweet用テキストの表示（ https://siv3d.github.io/reference/twitter/ ）

2021-10-01 09:29 UTC, Papyrustaro commented
@Jumpaku 
スコアファイルの保存とTweetボタンの配置まで実装しました。
お時間あるときに確認お願いします！

2021-10-01 10:21 UTC, Jumpaku commented
ハイスコアの読み込みはゲーム起動時に行うということですか？
もしそうなら，その仕様をドキュメントに記述しておいて欲しいです．

2021-10-01 10:31 UTC, Papyrustaro commented
@Jumpaku ハイスコアの仕様をドキュメントに記述しました。

2021-10-01 10:33 UTC, Jumpaku approved these changes

2021-10-01 10:33 UTC, merged