Feature/create result kura move
ParachanActionGame-Project/ParachanActionGame pull request #14
Opened 2021-10-03 02:17 UTC by Papyrustaro

2021-10-03 02:20 UTC, Jumpaku requested changes
クラちゃんの画像を使用して欲しいです．

2021-10-08 12:03 UTC, Jumpaku requested changes
クラちゃんの表示の実装ありがとうございます！レビューしました．以下の対応をお願いします！

* [x] クラちゃんの跳ね返りの当たり判定の中心と画像の中心を一致させる．
* [x] ResultParachanクラスのコンストラクタをコメントの通りにリファクタリングする．
* [x] 特別な理由がなければ，他のクラちゃんの画像（Kurachan_8.png，Kurachan_4.png）も追加する．
* [x] ResultScene.cppの64行目のバグを修正する．

```cpp
m_tweetButton.draw(ColorF(1.0, m_exitTransition.value())).drawFrame(2);
```

2021-10-10 13:35 UTC, Papyrustaro commented
@Jumpaku くらちゃんの画像の上下左右の余白を消してほしいです！余白があると、当たり判定がずれてしまいます。

2021-10-15 10:14 UTC, Jumpaku commented
余白を除いたクラちゃん画像の表示は別のプルリクでやる予定ですか？

2021-10-15 10:19 UTC, Jumpaku commented
余白を除いたクラちゃん画像の表示は*_crop.pngという名前の画像を使うように修正して欲しいです．

2021-10-15 10:25 UTC, merged

2021-10-15 10:26 UTC, Jumpaku commented
Thanks!