Game scene
ParachanActionGame-Project/ParachanActionGame pull request #21
Opened 2021-10-29 10:46 UTC by roro038

ゲームシーンのプルリクエスト

2021-10-29 11:09 UTC, Papyrustaro requested changes
1. [x] 一番小さいくらちゃんにカーソルを合わせたときにカーソルの見た目が変わってしまうと、「クリックできてしまう」と勘違いしてしまうので、カーソルの見た目を変えないようにしてほしいです！

2. [x] 制限時間の表記は、整数もしくは小数点第一位までで良いと思います！

2021-10-29 11:15 UTC, Jumpaku requested changes
* [x] GameSceneから遷移する前に音を消すようにしてください．

2021-10-30 01:55 UTC, Papyrustaro approved these changes

2021-10-30 02:01 UTC, Jumpaku requested changes

2021-10-30 02:01 UTC, Jumpaku commented on Game/Game/src/ParaSampleScene.cpp
> +		changeScene(State::Result);
ここで音を消す

2021-10-30 02:13 UTC, merged

2021-10-30 02:13 UTC, Jumpaku commented
Thanks!